// Configure your import map in config/importmap.rb. Read more: https://github.com/rails/importmap-rails
import "@hotwired/turbo-rails"
import "controllers"
import "@popperjs/core"
import "bootstrap"
import "mapkick/bundle"

var cities = [
  "Abbotsford",
  "Aberfeldie",
  "Albert Park",
  "Alphington",
  "Armadale",
  "Ascot Vale",
  "Balaclava",
  "Balwyn",
  "Balwyn North",
  "Bellfield",
  "Brunswick",
  "Brunswick East",
  "Brunswick West",
  "Burnley",
  "Camberwell",
  "Canterbury",
  "Carlton",
  "Carlton North",
  "Caulfield",
  "Caulfield East",
  "Caulfield North",
  "Caulfield South",
  "Clifton Hill",
  "Coburg",
  "Collingwood",
  "Cremorne",
  "Deepdene",
  "Docklands",
  "East Melbourne",
  "Elsternwick",
  "Elwood",
  "Essendon",
  "Essendon West",
  "Fairfield",
  "Fitzroy",
  "Fitzroy North",
  "Flemington",
  "Footscray",
  "Gardenvale",
  "Glen Iris",
  "Hawthorn",
  "Hawthorn East",
  "Ivanhoe",
  "Ivanhoe East",
  "Kensington",
  "Kew",
  "Kew East",
  "Kingsville",
  "Kooyong",
  "Maidstone",
  "Malvern",
  "Malvern East",
  "Maribyrnong",
  "Melbourne",
  "Middle Park",
  "Moonee Ponds",
  "Newport",
  "North Melbourne",
  "Northcote",
  "Parkville",
  "Pascoe Vale South",
  "Port Melbourne",
  "Prahran",
  "Preston",
  "Princes Hill",
  "Richmond",
  "Ripponlea",
  "Seddon",
  "South Kingsville",
  "South Melbourne",
  "South Wharf",
  "South Yarra",
  "Southbank",
  "Spotswood",
  "St Kilda",
  "St Kilda East",
  "St Kilda West",
  "Thornbury",
  "Toorak",
  "Tottenham",
  "Travancore",
  "West Footscray",
  "West Melbourne",
  "Williamstown",
  "Williamstown North",
  "Windsor",
  "Yarraville"
];

$(document).ready(function() {
  $('#area').autocomplete({
    source: cities,
    minLength: 2
  });
});
